name: 'ImmortalWrt Release Generic Script'
description: 'ImmortalWrt Release Generic Script'
runs:
  using: "composite"
  steps:
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: V${{ steps.get_version.outputs.version }}
          files: |
            immortalwrt-sdk-24.10.5-x86-64_gcc-13.3.0_musl.Linux-x86_64/bin/packages/*/base/*.ipk
            immortalwrt-sdk-25.12-SNAPSHOT-x86-64_gcc-14.3.0_musl.Linux-x86_64/bin/packages/*/base/*.apk
          body: |
            # This release by GitHub Actions
            > I'm lazy, so I'm too lazy to write update logs. As long as it runs, that's fine.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
