name: "Preparing build environment"
description: "Preparing build environment"
runs:
  using: "composite"
  steps:
    - name: Preparing build environment
      shell: bash
      run: |
          sudo apt update
          sudo apt install build-essential \
          gettext xsltproc python3-pyelftools
