name: 'Prepare SDK'
description: 'Unified SDK preparation for multiple architectures'
inputs:
  sdk_name:
    description: 'The full name of the SDK tarball (without extension)'
    required: true
runs:
  using: "composite"
  steps:
    - name: Download and Initialize SDK
      shell: bash
      run: |
        set -e

        wget --header="Host: l.867678.xyz" -O ${{ inputs.sdk_name }}.tar.zst https://23.95.28.150/${{ inputs.sdk_name }}.tar.zst

        tar -xvf ${{ inputs.sdk_name }}.tar.zst
        rm ${{ inputs.sdk_name }}.tar.zst
        cd ${{ inputs.sdk_name }}

        make defconfig
        ./scripts/feeds update -a
        ./scripts/feeds install -a
