name: 'Prepare SDK'
description: 'Unified SDK preparation for multiple architectures'
inputs:
  sdk_name:
    description: 'The full name of the SDK tarball (without extension)'
    required: true
runs:
  using: "composite"
  steps:
    - name: Download and Initialize SDK
      shell: bash
      run: |
        set -e

        wget --resolve=l.867678.xyz:443:23.95.28.150 -O ${{ inputs.sdk_name }}.tar.zst https://l.867678.xyz/${{ inputs.sdk_name }}.tar.zst

        tar -xvf ${{ inputs.sdk_name }}.tar.zst
        rm ${{ inputs.sdk_name }}.tar.zst
        cd ${{ inputs.sdk_name }}

        make defconfig
        ./scripts/feeds update -a
        ./scripts/feeds install -a
