name: 'Clone Source Code'
description: 'Clone Source Code'
inputs:
  project_name:
    required: true
  sdk_name:
    required: true
runs:
  using: "composite"
  steps:
    - name: Clone Source Code
      shell: bash
      run: |
          set -e

          cd ${{ inputs.sdk_name }}/package/
          git clone https://github.com/mokanove/${{ inputs.project_name }}.git
