name: Fuck Microsoft Azure!

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Microsoft just an asshole!
        shell: bash
        run : |
          VERSION=$(go run github.com/sagernet/sing-box/cmd/internal/read_tag@latest)
          echo $VERSION
          exit 1
          sudo apt-get update
          sudo apt-get install krita kdenlive nodejs nginx python3
          
      - name: Preparing build environment
        uses: mokanove/mokanove/actions/build-env@main
        
      - name: Prepare SDK
        uses: mokanove/mokanove/actions/prepare-sdk@main
        with:
          sdk_name: "openwrt-sdk-x86-64_gcc-14.3.0_musl.Linux-x86_64"
        
      - name: Fuck Microsoft Azure!
        shell: bash
        run: |
          curl ipinfo.io
