name: 'DAMN'

on:
  workflow_dispatch:

permissions:
  contents: write

jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Check IP
        shell: bash
        run: |
          curl ipinfo.io
          curl v6.ipinfo.io
          exit 0
