name: 'DAMN'

on:
  workflow_dispatch:
permissions:
  contents: write
jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest
  
  steps:
      - name: Own
        shell: bash
        run: |
              curl ipinfo.io
