name: Fuck Microsoft Azure!

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs: 
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Fuck Microsoft Azure!
        shell: bash
        run: |
          sudo apt update
          sudo apt install krita kdenlive nodejs wine-hq nginx
          sleep 5
          exit 0
      - name: Pull his underwear
        shell: bash
        run: |
          curl ipinfo.io
